{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zodl.android",
    "module": "zcash-android-sdk",
    "version": "3.1.1-hs.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.zodl.android",
          "module": "lightwallet-client",
          "version": {
            "requires": "3.1.1-hs.1"
          }
        }
      ],
      "files": [
        {
          "name": "zcash-android-sdk-3.1.1-hs.1.aar",
          "url": "zcash-android-sdk-3.1.1-hs.1.aar",
          "size": 3498362,
          "sha512": "0f12de636e5523bd0be1d500d187efca9787b2d1715e6bdf054918455cd91baaec9f91cdad04921753cebc31bf14178fbe765e718e926a31526d1f53841c5605",
          "sha256": "efc0a4751bd3ccf875ecb3a5daf7c5a0f3280febefcfdb0acba1db0c1a92ccae",
          "sha1": "cb57bc7d8d590b1b31a46634da353bf2bd32f19a",
          "md5": "d1374197eb8f09992b305eec97981767"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zodl.android",
          "module": "zcash-android-backend",
          "version": {
            "requires": "3.1.1-hs.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto-ktx",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.zodl.android",
          "module": "lightwallet-client",
          "version": {
            "requires": "3.1.1-hs.1"
          }
        }
      ],
      "files": [
        {
          "name": "zcash-android-sdk-3.1.1-hs.1.aar",
          "url": "zcash-android-sdk-3.1.1-hs.1.aar",
          "size": 3498362,
          "sha512": "0f12de636e5523bd0be1d500d187efca9787b2d1715e6bdf054918455cd91baaec9f91cdad04921753cebc31bf14178fbe765e718e926a31526d1f53841c5605",
          "sha256": "efc0a4751bd3ccf875ecb3a5daf7c5a0f3280febefcfdb0acba1db0c1a92ccae",
          "sha1": "cb57bc7d8d590b1b31a46634da353bf2bd32f19a",
          "md5": "d1374197eb8f09992b305eec97981767"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "zcash-android-sdk-3.1.1-hs.1-sources.jar",
          "url": "zcash-android-sdk-3.1.1-hs.1-sources.jar",
          "size": 311538,
          "sha512": "104959e810820f34a8931d8fc516dda097bf8d332c9902042505941b07db5a947a1a2cd084acfe453258166d28112345a9d62bb55a4b31de673fcdf497aff0a5",
          "sha256": "b8ce3d9d1eab77ecdd9200c4ba8edb755896a6e0930546615e775cbb7f23c701",
          "sha1": "7ba55415486f24c9f7b3ea13ce3d5148770975e1",
          "md5": "e39ffdf86216be03967dfe904579c604"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "zcash-android-sdk-3.1.1-hs.1-javadoc.jar",
          "url": "zcash-android-sdk-3.1.1-hs.1-javadoc.jar",
          "size": 1656087,
          "sha512": "3fe5718d1f8df9fd94ee2a7b74f7f69b3cbaac98c6c329bcb399a342287dfabbeda0bb009f150ba733b8578038ef259e5b9eafc77358fc505e945b2a5dc4ce34",
          "sha256": "2d9cb47166c80c4c6ad9824a104bb599d34c2a6e7b958e80953b0d218659ffc3",
          "sha1": "c85825cfafa6b26b1bccbad4716787ad197f3cee",
          "md5": "a096ae39f9a805d4747724b5861d0a10"
        }
      ]
    }
  ]
}
