{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zodl.android",
    "module": "zcash-android-sdk",
    "version": "3.2.0-hs.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.zodl.android",
          "module": "lightwallet-client",
          "version": {
            "requires": "3.2.0-hs.1"
          }
        }
      ],
      "files": [
        {
          "name": "zcash-android-sdk-3.2.0-hs.1.aar",
          "url": "zcash-android-sdk-3.2.0-hs.1.aar",
          "size": 3514244,
          "sha512": "36f574965a0edc840536ec773e139f9bfb81cdb106df746cc065864dbb5dcf098b3f93c11f27b3e1c78d6264a737fae9ea7d7c4bf85c20751cce9014c86fd61a",
          "sha256": "51df28bb60a87aeaa43866fa1a24cb7770362563067cfcded47efac8d365ad7a",
          "sha1": "ade984af9b1ad27d7195d6b03694cffa73c9d51b",
          "md5": "314b58e0196d85b4d024e9742e60b0f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zodl.android",
          "module": "zcash-android-backend",
          "version": {
            "requires": "3.2.0-hs.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto-ktx",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.zodl.android",
          "module": "lightwallet-client",
          "version": {
            "requires": "3.2.0-hs.1"
          }
        }
      ],
      "files": [
        {
          "name": "zcash-android-sdk-3.2.0-hs.1.aar",
          "url": "zcash-android-sdk-3.2.0-hs.1.aar",
          "size": 3514244,
          "sha512": "36f574965a0edc840536ec773e139f9bfb81cdb106df746cc065864dbb5dcf098b3f93c11f27b3e1c78d6264a737fae9ea7d7c4bf85c20751cce9014c86fd61a",
          "sha256": "51df28bb60a87aeaa43866fa1a24cb7770362563067cfcded47efac8d365ad7a",
          "sha1": "ade984af9b1ad27d7195d6b03694cffa73c9d51b",
          "md5": "314b58e0196d85b4d024e9742e60b0f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "zcash-android-sdk-3.2.0-hs.1-sources.jar",
          "url": "zcash-android-sdk-3.2.0-hs.1-sources.jar",
          "size": 311539,
          "sha512": "26cd0ea88401a441a46e5e11cd68cf135d7162ce7e94e39f48f9f044ca5a35276be7f3068099e398d14af4cf440c4395067a21996ced4af48771ab01e0a348b1",
          "sha256": "908e64e4b5090da22f67877a631a9d0a904918cb7638296b91da1e924186f434",
          "sha1": "3a5374efa1d34f0544e176ce45fd7650cfef487a",
          "md5": "9d769b30bd28ca6dac0c556d8dcda0e3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "zcash-android-sdk-3.2.0-hs.1-javadoc.jar",
          "url": "zcash-android-sdk-3.2.0-hs.1-javadoc.jar",
          "size": 1656094,
          "sha512": "75b77dd795f9d0bba2fdd6873b7ecbbe110be8b63f82a9fd70b3a5c423d4457c227e76158e40a954f20af9aaa81d76fc9e8350245843c0ba3553da1340642de1",
          "sha256": "924cc99aac2ff9191ba2c58b509bed317aca34a1b873c3dbca448b82046f46a3",
          "sha1": "6b0ec54f8ae99106c2f0fd2bc4a56aaeb5cabfbc",
          "md5": "acdcd4985e19d94be2fffaea86f578c0"
        }
      ]
    }
  ]
}
