{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zodl.android",
    "module": "zcash-android-backend",
    "version": "3.2.0-hs.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.zodl.android",
          "module": "lightwallet-client",
          "version": {
            "requires": "3.2.0-hs.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "zcash-android-backend-3.2.0-hs.1.aar",
          "url": "zcash-android-backend-3.2.0-hs.1.aar",
          "size": 77344365,
          "sha512": "c47cb6346f43f0bfb520085df5d3cdfe749d2f9f5f4b843e11dd39606241e464a9f3ecd1a72474a88731eb765406beba6fda570deded96c556de33226f0c3e75",
          "sha256": "6af3b94bba8b1a03e41cc4af146d5db0b9c3f604557bb92836dbc14e69ee4ca4",
          "sha1": "d126f4033026999d2405369e47998465c92ba360",
          "md5": "510f8ac604b35f5f08b9c387b7916ec5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin-lite",
          "version": {
            "requires": "4.34.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf-lite",
          "version": {
            "requires": "1.78.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.zodl.android",
          "module": "lightwallet-client",
          "version": {
            "requires": "3.2.0-hs.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "zcash-android-backend-3.2.0-hs.1.aar",
          "url": "zcash-android-backend-3.2.0-hs.1.aar",
          "size": 77344365,
          "sha512": "c47cb6346f43f0bfb520085df5d3cdfe749d2f9f5f4b843e11dd39606241e464a9f3ecd1a72474a88731eb765406beba6fda570deded96c556de33226f0c3e75",
          "sha256": "6af3b94bba8b1a03e41cc4af146d5db0b9c3f604557bb92836dbc14e69ee4ca4",
          "sha1": "d126f4033026999d2405369e47998465c92ba360",
          "md5": "510f8ac604b35f5f08b9c387b7916ec5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "zcash-android-backend-3.2.0-hs.1-sources.jar",
          "url": "zcash-android-backend-3.2.0-hs.1-sources.jar",
          "size": 103408,
          "sha512": "39095ebf24c299577b3cd538804e8b21506c28e5fe8c12bfc3b54486a262bc87b84996ef26171cb2742c2875af4b13b5a839e278652ad38829b09e7588619e55",
          "sha256": "9634a9e5d1fabcbdc8b8449957493848d0a1ab0fedffca9ca38fb5a9235e5e1d",
          "sha1": "cb3cbdb5b2df78fdfbc886caf77ef6cac8719888",
          "md5": "2cd2a544f972bd7b4d849f1b82008309"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "zcash-android-backend-3.2.0-hs.1-javadoc.jar",
          "url": "zcash-android-backend-3.2.0-hs.1-javadoc.jar",
          "size": 1140251,
          "sha512": "af648633f7b044ffed07626043a2d885c2b4f3bc446cf57709538aa24b1ee55db67e79dbbeccd284900f8f9a27e84fea492b32e74014a795a55351f45a8bd2d4",
          "sha256": "5b736e85f126efedcf1556804e8bc335c34480939d8eca8a645aa4a50c8f6161",
          "sha1": "949310d3a22dc2b5fab268655caf8f028ab102be",
          "md5": "3720aa6b87dd9599b5b71b8ceac2abc1"
        }
      ]
    }
  ]
}
